import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import { Toaster } from "@/components/ui/sonner";
import NetworkProvider from "@/components/shared/NetworkProvider";
import { SITE_URL } from "@/lib/constants";
import { NextIntlClientProvider } from "next-intl";
import RouteProgress from "@/components/shared/RouteProgress";
import { getLocale } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // Absolute base for og:image and canonical URLs. Link previews (WhatsApp,
  // Slack, X) reject relative image paths, so this must be set.
  metadataBase: new URL(SITE_URL),

  title: {
    default: "ReadAM | AI-powered exam prep for Cameroonian students",
    // Pages set their own title; this wraps it. e.g. "Contact | ReadAM"
    template: "%s | ReadAM",
  },
  description:
    "Study for the GCE and Baccalauréat with an AI tutor that explains step by step, thousands of past questions, and video courses from verified Cameroonian teachers.",
  applicationName: "ReadAM",
  keywords: [
    "ReadAM", "GCE", "Baccalauréat", "Cameroon", "past questions",
    "AI tutor", "O Level", "A Level", "revision", "exam prep",
  ],
  authors: [{ name: "ReadAM" }],
  creator: "ReadAM",
  publisher: "ReadAM",

  alternates: { canonical: "/" },

  openGraph: {
    type: "website",
    siteName: "ReadAM",
    locale: "en_GB",
    url: SITE_URL,
    title: "ReadAM | AI-powered exam prep for Cameroonian students",
    description:
      "An AI tutor that explains step by step, past questions, and video courses mapped to the GCE and Baccalauréat syllabi. Built for students in Cameroon.",
    // The card itself is generated by src/app/opengraph-image.tsx
  },

  twitter: {
    card: "summary_large_image",
    title: "ReadAM | AI-powered exam prep for Cameroonian students",
    description:
      "An AI tutor that explains step by step, past questions, and video courses mapped to the GCE and Baccalauréat syllabi.",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },

  formatDetection: { telephone: false },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Resolved from the locale cookie, so the served HTML is already in the
  // chosen language and <html lang> matches it for screen readers and search.
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>
          <NetworkProvider />
          <RouteProgress />

          {children}

          <Toaster richColors position="top-right" closeButton />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
