import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import { Toaster } from "@/components/ui/sonner";
import NetworkProvider from "@/components/shared/NetworkProvider";
import { SITE_URL } from "@/lib/constants";
import { NextIntlClientProvider } from "next-intl";
import RouteProgress from "@/components/shared/RouteProgress";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { LOCALES, isLocale } from "@/i18n/locales";
import ServiceWorkerRegister from "@/components/shared/ServiceWorkerRegister";
import InstallPrompt from "@/components/shared/InstallPrompt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // Absolute base for og:image and canonical URLs. Link previews (WhatsApp,
  // Slack, X) reject relative image paths, so this must be set.
  metadataBase: new URL(SITE_URL),

  title: {
    default: "ReadAM | AI-powered exam prep for Cameroonian students",
    // Pages set their own title; this wraps it. e.g. "Contact | ReadAM"
    template: "%s | ReadAM",
  },
  description:
    "Study for the GCE and Baccalauréat with an AI tutor that explains step by step, thousands of past questions, and video courses from verified Cameroonian teachers.",
  applicationName: "ReadAM",
  keywords: [
    "ReadAM", "GCE", "Baccalauréat", "Cameroon", "past questions",
    "AI tutor", "O Level", "A Level", "revision", "exam prep",
  ],
  authors: [{ name: "ReadAM" }],
  creator: "ReadAM",
  publisher: "ReadAM",

  alternates: { canonical: "/" },

  openGraph: {
    type: "website",
    siteName: "ReadAM",
    locale: "en_GB",
    url: SITE_URL,
    title: "ReadAM | AI-powered exam prep for Cameroonian students",
    description:
      "An AI tutor that explains step by step, past questions, and video courses mapped to the GCE and Baccalauréat syllabi. Built for students in Cameroon.",
    // Generated by src/app/opengraph-image.tsx. Referenced explicitly
    // because that file sits outside the [locale] segment, so Next's
    // file convention no longer attaches it on its own. Keeping it at
    // /opengraph-image (rather than /en/opengraph-image) means previews
    // already cached by WhatsApp, Slack and X keep resolving.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "ReadAM, AI-powered exam prep for Cameroonian students",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    images: ["/opengraph-image"],
    title: "ReadAM | AI-powered exam prep for Cameroonian students",
    description:
      "An AI tutor that explains step by step, past questions, and video courses mapped to the GCE and Baccalauréat syllabi.",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },

  formatDetection: { telephone: false },

  // iOS reads these instead of the web app manifest — Safari doesn't support
  // the manifest icon/display spec, so "Add to Home Screen" falls back to
  // these meta tags for a standalone (no browser chrome) launch.
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "ReadAM",
  },
  icons: {
    // Same reasoning as the Open Graph card above: src/app/icon.tsx is
    // outside the [locale] segment, so it needs naming explicitly.
    icon: [{ url: "/icon", type: "image/png", sizes: "32x32" }],
    apple: "/icons/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#2563EB",
};

/**
 * Pre-render both locales at build time. This is the whole point of the
 * [locale] segment: the locale comes from the route, not from a cookie, so
 * these pages can be static instead of a fresh serverless render per visit.
 */
export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  // Tells next-intl which locale this render is for without reading cookies.
  // Reading cookies here is what previously opted every route in the app into
  // dynamic rendering, since this is the root layout.
  setRequestLocale(locale);

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>
          <NetworkProvider />
          <RouteProgress />
          <ServiceWorkerRegister />

          {children}

          <InstallPrompt />
          <Toaster richColors position="top-right" closeButton />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
